drivers: gpio-keys: fix type specifier missing
fix a compilation error ignored by gnu89:

../drivers/input/keyboard/gpio_keys.c:1038:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
gpio_keys_button_enable_wakeup(struct gpio_button_data *bdata)
^
1 error generated.

Defining it as static int pleases the compiler

Signed-off-by: maxsteeel <109047395+maxsteeel@users.noreply.github.com>